### ISSUE TITLE
Hina integration

### ISSUE THREAD

**Issue by RobbWatershed** [RobbWatershed/GalleryCherry#23]
https://github.com/ixilia/hina

An HTTP cache of 5 hours has to be enabled when downloading images on other domains than `.ixil.cc`
No limit on the API or on `.ixil.cc`-hosted images

https://www.cloudflare.com/learning/cdn/glossary/what-is-cache-control/

**Comment by assintates** [comment]
Please check for IP blocking of image servers other than `.ixil.cc` some image servers might be blocked in few countries.

**Comment by assintates** [comment]
Repository has been moved to https://github.com/ixilia/hina

**Comment by RobbWatershed** [comment]
Integration of Retrofit with LiveData & PagedList

https://blog.fossasia.org/implementing-pagination-with-retrofit-in-eventyay-attendee/

https://medium.com/@sunnysultan1640/android-paging-library-tutorial-with-retrofit-using-mvvm-architecture-f02b5c15e8bc
