### ISSUE TITLE
Where's local.properties file and which properties should it have?

### ISSUE THREAD

**Issue by UltraBurstXD** [RobbWatershed/GalleryCherry#31]
Hi,

I'm trying to build the project and test some stuff, but it seems `local.properties` file is missing and I'm unable to build the project successfully... BTW, which codes should it have? I'm having issues with environment variable **rapidapiKey** and **meiliRouter**

**Comment by RobbWatershed** [comment]
You can create a blank file named `local.properties` in the project's root file. These keys are private between the API owner and myself. Hina doesn't work at the moment anyway.....

**Comment by UltraBurstXD** [comment]
I understand.

**Rapidapi** key I could get one in https://rapidapi.com/, but where I could get **meiliRouter** key?

**Comment by RobbWatershed** [comment]
1/ These keys are the ones the owner of Hina gave me to authenticate the app on his APIs. I'm not allowed to share them.

I know that makes the app non-FOSS but I don't really care about that 😋 


2/ These services are down at the moment anyway. If you're forking the app to fix Hina, just let me know, it will be way faster for me to check with the owner 😉
